filebeat.inputs:
- type: container
  paths:
  - /var/log/containers/*.log
  json:
    keys_under_root: true
    message_key: message
    ignore_decoding_error: true
    overwrite_keys: true
  fields_under_root: true
  index: logs-akingbee
  fields:
    app: akb
  processors:
  - add_kubernetes_metadata:
      host: ${NODE_NAME}
      matchers:
      - logs_path:
          logs_path: "/var/log/containers/"
  - drop_event:
      when:
        not:
          has_fields: ['name']

processors:
- add_cloud_metadata:
- add_host_metadata:

output.elasticsearch:
  hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}