version: "2"
linters:
  default: all
  disable:
    - depguard
    - dupl
    - exhaustruct
    - funlen
    - gochecknoglobals
    - mnd
    - sqlclosecheck
    - testpackage
    - wrapcheck
  settings:
    gosec:
      excludes:
        - G101
        - G201
        - G203
    nlreturn:
      block-size: 2
    wsl:
      allow-cuddle-declarations: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
