def init():
    global errorMsg, successMsg
    
    bodyUnknown = {'fr': "Une erreur est survenue lors du traitement de votre demande, merci de contacter kingbee.root@gmail.com si l'erreur persiste",
                  'en': "An error happened while processing your request. Please contact kingbee.root@gmail.com should this error persists"}
    emptyTitle = {'fr': '', 'en': ''}

    errorMsg = {
        '00001': bodyUnknown,
        '00002': {'fr': "Cet utilisateur n'existe pas",
                  'en': "This user does not exist"},
        '00003': {'fr': "Le mot de passe fournit est incorrect",
                 'en': "The provided password is incorrect"},
        '00004': bodyUnknown, 
        '00005': {'fr': "Ce nom d'utilisateur est déjà utilisé, merci d'en choisir un autre",
                  'en': "This username is already taken, please chose another one"},
        '00006': {'fr': "Cet email est déjà utilisé, merci d'en choisir un autre",
                  'en': "This email is already in use, please chose another one"},
        '00007': bodyUnknown,
        '00008': bodyUnknown,
        '00009': bodyUnknown,
        '00010': bodyUnknown,
        '00011': bodyUnknown,
        '00012': {'fr': "Cet utilisateur n'existe pas",
                  'en': "This user does not exist"},
        '00013': bodyUnknown,
        '00014': bodyUnknown,
        '00015': bodyUnknown,
        '00016': bodyUnknown,
        '00017': bodyUnknown,
        '00018': bodyUnknown,
        '00019': bodyUnknown,
        '00020': bodyUnknown,
        '00021': bodyUnknown,
        '00022': bodyUnknown,
        '00023': bodyUnknown,
        '00024': bodyUnknown,
        '00025': bodyUnknown,
        '00026': bodyUnknown,
        '00027': bodyUnknown,
        '00028': bodyUnknown,
        '00029': bodyUnknown,
        '00030': bodyUnknown,
        '00031': {'fr': "L'entrée est vide",
                  'en': "The entry is empty"}
        }

    successMsg = {
        '00001': {'body': {'fr': "Vous êtes connecté",
                           'en': "You are connected"},
                  'title': {'fr': "Bonjour !",
                            'en': "Hello !"}},
        '00002': {'body': {'fr': "Vous êtes bien enregistré",
                           'en': "You are now registered"},
                  'title': {'fr': "Bienvenue !",
                            'en': "Welcome !"}},
        '00003': {'body': {'fr': "Votre mot de passe a bien été réinitialisé",
                           'en': "Your password has been reseted"},
                  'title': emptyTitle},
        '00004': {'body': {'fr': "Type de miel ajouté avec succés !",
                           'en': "Honey type successfully added !"},
                  'title': emptyTitle},
        '00005': {'body': {'fr': "Status de ruche créé avec succés !",
                           'en': "Beehouse status created with success !"},
                  'title': emptyTitle},
        '00006': {'body': {'fr': "Apiculteur créé avec succés !",
                           'en': "Beekeeper created with success !"},
                  'title': emptyTitle},
        '00007': {'body': {'fr': "Ruche créée avec succés !",
                           'en': "Beehouse created with success !"},
                  'title': emptyTitle},
        '00008': {'body': {'fr': "Etat de santé créée avec succés !",
                           'en': "Health status created with success !"},
                  'title': emptyTitle},
        '00009': {'body': {'fr': "Status de ruche créée avec succés !",
                           'en': "Beehouse status created with success !"},
                  'title': emptyTitle},
        '00010': {'body': {'fr': "Ruche modifiée avec succés !",
                           'en': "Beehouse updated with success !"},
                  'title': emptyTitle},
        '00011': {'body': {'fr': "Commentaire ajouté avec succés !",
                           'en': "Commentary successfully added !"},
                  'title': emptyTitle},
        '00012': {'body': {'fr': "Action planifiée avec succés !",
                           'en': "Action planified successfully !"},
                  'title': emptyTitle},
        '00013': {'body': {'fr': "Action résolue avec succés !",
                           'en': "Action solved successfully !"},
                  'title': emptyTitle},
        '00014': {'body': {'fr': "Commentaire modifié avec succés !",
                           'en': "Commentary successfully modified !"},
                  'title': emptyTitle},
        '00015': {'body': {'fr': "Commentaire supprimé avec succés !",
                           'en': "Commentary successfully deleted !"},
                  'title': emptyTitle},
        '00016': {'body': {'fr': "Donnée modifiée avec succés !",
                           'en': "Data successfully modified !"},
                  'title': emptyTitle},
        '00017': {'body': {'fr': "Donnée supprimée avec succés !",
                           'en': "Data successfully deleted !"},
                  'title': emptyTitle},
        '00018': {'body': {'fr': "Donnée ajoutée avec succés !",
                           'en': "Data successfully added !"},
                  'title': emptyTitle},
        '00019': {'body': {'fr': "Rucher modifié avec succés !",
                           'en': "Apiary successfully amended !"},
                  'title': emptyTitle},
        '00020': {'body': {'fr': "Rucher supprimé avec succés !",
                           'en': "Apiary successfully deleted !"},
                  'title': emptyTitle}
        }

