service_name = "akingbee"

[development]
database_host = "localhost"
database_port = 5432
database_user = "akingbee"
database_password = "123"
database_dbname = "akingbee"

cerbes_api_endpoint = "localhost"
cerbes_api_port = 9001

[test]
database_host = "localhost"
database_port = 5432
database_user = "akingbee"
database_password = "123"
database_dbname = "postgres"

