version: "3.7"

services:

  poseidon:
    image: yomain/poseidon:latest
    container_name: poseidon
    ports:
      - 8080:80
    networks:
      - akb

  cerbes:
    image: yomain/cerbes:latest
    container_name: cerbes
    environment:
      - CERBES_ENV=local
      - EXECUTE_MIGRATION=true
      - CERBES__DATABASE__URL=postgres://sa_cerbes:password@db/cerbes
    ports:
      - 9001:80
    depends_on: [db]
    restart: always
    networks:
      - akb

  aristaeus-api:
    image: yomain/aristaeus:latest
    container_name: aristeaus-api
    environment:
      - EXECUTE_MIGRATION=true
      - SERVICE_NAME=aristaeus-api
      - AKB_DATABASE_HOST=db
      - AKB_DATABASE_USER=sa_aristaeus
      - AKB_DATABASE_PASSWORD=123
      - AKB_DATABASE_DBNAME=aristaeus
      - AKB_CERBES_API_ENDPOINT=http://cerbes
      - AKB_CERBES_API_PORT=80
    ports:
      - 9002:80
    depends_on: [db, cerbes]
    restart: always
    networks:
      - akb

  aristaeus-listener:
    image: yomain/aristaeus:latest
    container_name: aristeaus-listener
    environment:
      - SERVICE_NAME=aristaeus-listener
      - AKB_DATABASE_HOST=db
      - AKB_DATABASE_USER=sa_aristaeus
      - AKB_DATABASE_PASSWORD=123
      - AKB_DATABASE_DBNAME=aristaeus
    command: python aristaeus/controllers/consumers/app.py
    depends_on: [db]
    restart: always
    networks:
      - akb

  migration:
    image: yomain/gaea:latest
    container_name: migration
    environment:
      - SERVICE_NAME=migration
      - AKB_DATABASE_HOST=db
      - AKB_DATABASE_USER=akingbee
      - AKB_DATABASE_PASSWORD=123
      - AKB_DATABASE_DBNAME=akb_dev
    depends_on: [db]
    networks:
      - akb

  db:
    image: postgres:10-alpine
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      ARISTAEUS_USERNAME: aristaeus
      ARISTAEUS_PASSWORD: 123
      CERBES_USERNAME: cerbes
      CERBES_PASSWORD: 123
    volumes:
      - ./infra/core/config/postgresql/users.sh:/docker-entrypoint-initdb.d/users.sh
    networks:
      - akb

networks:
    akb:

