version: "3.7"

services:

  poseidon:
    image: yomain/poseidon:latest
    container_name: poseidon
    ports:
      - 8080:80
    networks:
      - akb

  cerbes:
    image: yomain/cerbes:latest
    container_name: cerbes
    environment:
      - AKB_DATABASE_HOST=db
      - AKB_DATABASE_DBNAME=cerbes
      - AKB_DATABASE_USER=sa_cerbes
      - AKB_RBMQ_USER=akingbee
      - AKB_RBMQ_PASSWORD=password
      - AKB_RBMQ_HOST=rbmq
      - AKB_RBMQ_PORT=5672
      - AKB_RBMQ_VHOST=/
    ports:
      - 9001:9001
    depends_on: [db, rbmq]
    restart: always
    networks:
      - akb

  aristaeus-api:
    image: yomain/aristaeus2:latest
    container_name: aristeaus-api
    environment:
      - SERVICE_NAME=aristaeus-api
      - AKB_DATABASE_HOST=db
      - AKB_DATABASE_USER=sa_aristaeus
      - AKB_DATABASE_PASSWORD=123
      - AKB_DATABASE_DBNAME=aristaeus
      - AKB_CERBES_ENDPOINT=http://cerbes:9001
    ports:
      - 9002:80
    depends_on: [db, rbmq, cerbes]
    restart: always
    networks:
      - akb

  aristaeus-listener:
    image: yomain/aristaeus2:latest
    container_name: aristeaus-listener
    environment:
      - SERVICE_NAME=aristaeus-listener
      - AKB_DATABASE_HOST=db
      - AKB_DATABASE_USER=sa_aristaeus
      - AKB_DATABASE_PASSWORD=123
      - AKB_DATABASE_DBNAME=aristaeus
      - AKB_RBMQ_HOST=rbmq
      - AKB_RBMQ_PORT=5672
      - AKB_RBMQ_USER=akingbee
      - AKB_RBMQ_PASSWORD=password
      - AKB_RBMQ_VHOST=/
      - AKB_RBMQ_EXCHANGE=akingbee.main_exchange
      - AKB_RBMQ_EXCHANGE_TYPE=topic
      - AKB_RBMQ_QUEUE=aristaeus-main-queue
    command: python aristaeus/controllers/consumers/app.py
    depends_on: [db, rbmq]
    restart: always
    networks:
      - akb

  migration:
    image: yomain/gaea:latest
    container_name: migration
    environment:
      - SERVICE_NAME=migration
      - AKB_DATABASE_HOST=db
      - AKB_DATABASE_USER=akingbee
      - AKB_DATABASE_PASSWORD=123
      - AKB_DATABASE_DBNAME=akb_dev
    depends_on: [db, rbmq]
    networks:
      - akb

  db:
    image: postgres:10-alpine
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      ARISTAEUS_USERNAME: aristaeus
      ARISTAEUS_PASSWORD: 123
      CERBES_USERNAME: cerbes
      CERBES_PASSWORD: 123
    volumes:
      - ./infra/core/config/postgresql/users.sh:/docker-entrypoint-initdb.d/users.sh
    networks:
      - akb

  rbmq:
    image: rabbitmq:management-alpine
    container_name: rbmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: akingbee
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - akb

networks:
    akb:

