env = "local"
hash_key = "very_super_secret_key"
jwt_key = "very_super_secret_key"

[app]
port = 8000

[database]
url = "postgres://sa_cerbes:123@localhost:5432/cerbes"

[rabbitmq]
host = "localhost"
port = 5672
user = "akingbee"
password = "password"
exchange = "akingbee.main_exchange"
vhost = "/"
