"""add reset_id field for credentials

Revision ID: 0ac840331a60
Revises: d686c3a72adb
Create Date: 2021-03-20 12:59:40.199383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0ac840331a60"
down_revision = "d686c3a72adb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "credentials",
        sa.Column("reset_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credentials", "reset_id")
    # ### end Alembic commands ###
