"""add activation_id field for users

Revision ID: a10943d731da
Revises: 8d9f03d62087
Create Date: 2021-03-14 23:00:06.310171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a10943d731da'
down_revision = '8d9f03d62087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activation_id', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_id')
    # ### end Alembic commands ###
