"""add activated field for users

Revision ID: d686c3a72adb
Revises: a10943d731da
Create Date: 2021-03-17 23:54:24.037699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d686c3a72adb"
down_revision = "a10943d731da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("activated", sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "activated")
    # ### end Alembic commands ###
