apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  ports:
  - port: 9200
    targetPort: 9200
    name: port1
  - port: 9300
    targetPort: 9300
    name: port2
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      volumes:
      # - name: data
      #   persistentVolumeClaim:
      #     claimName: elasticsearch-data
      - name: config
        configMap:
          defaultMode: 0640
          name: elastic-config
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        # - mountPath: /usr/share/elasticsearch/data
        #   name: data
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          readOnly: true
          subPath: elasticsearch.yml
        env:
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secrets-config
              key: ELASTIC_PASSWORD

