apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  ports:
  - port: 9200
    targetPort: 9200
    name: port1
  - port: 9300
    targetPort: 9300
    name: port2
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 0
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-data
      - name: elasticsearch-config
        configMap:
          defaultMode: 0660
          name: elasticsearch-config
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: elastic-node
                operator: Exists
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          readOnly: true
          subPath: elasticsearch.yml
        env:
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secrets-config
              key: ELASTIC_PASSWORD

---
apiVersion: v1
kind: Pod
metadata:
  name: provision-elasticsearch
  labels:
    app: provision-elasticsearch
spec:
  securityContext:
    fsGroup: 0
  volumes:
  - name: provision-elasticsearch
    configMap:
      defaultMode: 0770
      name: provision-elasticsearch
  - name: wait-for-it
    configMap:
      defaultMode: 0770
      name: wait-for-it
  restartPolicy: OnFailure
  containers:
  - name: provision-elasticsearch
    image: ellerbrock/alpine-bash-curl-ssl
    command: ["/script/wait-for-it.sh", "-t", "300", "elasticsearch:9200", "--", "/app/provision-elasticsearch.sh"]
    volumeMounts:
    - name: wait-for-it
      mountPath: /script
      readOnly: true
    - name: provision-elasticsearch
      mountPath: /app
      readOnly: true
    env:
    - name: ELASTIC_HOST
      value: elasticsearch:9200
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: env-secrets-config
          key: ELASTIC_PASSWORD
    - name: KIBANA_SYSTEM_PASSWORD
      valueFrom:
        secretKeyRef:
          name: env-secrets-config
          key: KIBANA_SYSTEM_PASSWORD
    - name: BEATS_SYSTEM_PASSWORD
      valueFrom:
        secretKeyRef:
          name: env-secrets-config
          key: BEATS_SYSTEM_PASSWORD
    - name: KIBANA_YOMAIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: env-secrets-config
          key: KIBANA_YOMAIN_PASSWORD


