configMapGenerator:
- name: elasticsearch-config
  files:
  - conf/elasticsearch.yml
- name: provision-elasticsearch
  files:
  - conf/provision-elasticsearch.sh
- name: kibana-config
  files:
  - conf/kibana.yml
- name: filebeat-config
  files:
  - conf/filebeat.yml


resources:
  - elasticsearch.yaml
  - kibana.yaml
  - filebeat.yaml