configMapGenerator:
- name: elasticsearch-config
  files:
  - conf/elasticsearch.yml
- name: kibana-config
  files:
  - conf/kibana.yml
- name: filebeat-config
  files:
  - conf/filebeat.yml
- name: jvm-config
  files:
  - conf/jvm.options


resources:
  - elasticsearch.yaml
  - kibana.yaml
  - filebeat.yaml