SQL_PROCESSING_ERROR = 1
USER_NOT_FOUND_ERROR = 2
INCORRECT_PASSWORD_ERROR = 3
USER_ALREADY_EXISTS_ERROR = 4
EMAIL_ALREADY_EXISTS_ERROR = 5
TRANSLATION_ID_DOES_NOT_EXISTS = 6
USERS_MIXED_UP_ERROR = 7


LOGIN_SUCCESS = 1
REGISTER_SUCCESS = 2
PASSWORD_RESET_SUCCESS = 3
NEW_PARAMETER_SUCCESS = 4
NEW_BEEHOUSE_SUCCESS = 5
NEW_BEEKEEPER_SUCCESS = 6
MODIFICATION_SUCCESS = 7
ACTION_PLANIFICATION_SUCCESS = 8
ACTION_SOLVED_SUCCESS = 9
DELETION_SUCCESS = 10
