from src.constants.config import FRENCH, ENGLISH

traductions = {
    1: {
        FRENCH: "Nom d'utilisateur ou mot de passe incorrect",
        ENGLISH: "Wrong username or password",
    },
    2: {FRENCH: "Nom d'utilisateur", ENGLISH: "Username"},
    3: {FRENCH: "Mot de passe", ENGLISH: "Password"},
    4: {FRENCH: "Se connecter", ENGLISH: "Log in"},
    5: {FRENCH: "Ruches", ENGLISH: "Hives"},
    6: {FRENCH: "Ruchers", ENGLISH: "Apiaries"},
    7: {FRENCH: "Paramètre", ENGLISH: "Set up"},
    8: {FRENCH: "Inscription", ENGLISH: "Register"},
    10: {FRENCH: "Déconnexion", ENGLISH: "Log out"},
    11: {FRENCH: "Connexion", ENGLISH: "Log in"},
    12: {FRENCH: "Langage", ENGLISH: "Language"},
    13: {
        FRENCH: "Confirmer le mot de passe",
        ENGLISH: "Confirm your password",
    },
    14: {FRENCH: "Valider", ENGLISH: "Submit"},
    15: {FRENCH: "Email", ENGLISH: "Email"},
    16: {
        FRENCH: "Utilisez seulement des lettres et des nombres !",
        ENGLISH: "Only use letters and numbers !",
    },
    17: {
        FRENCH: "Il faut un email valide",
        ENGLISH: "Insert a valid email address",
    },
    18: {
        FRENCH: "Utilisez au moins 8 caractères",
        ENGLISH: "Must have 8 or more characters",
    },
    19: {FRENCH: "Connecté en tant que", ENGLISH: "Logged in as"},
    20: {FRENCH: "Créer un rucher", ENGLISH: "New Apiary"},
    21: {FRENCH: "Création d'un rucher", ENGLISH: "Creation of an apiary"},
    22: {FRENCH: "Nom", ENGLISH: "Name"},
    23: {FRENCH: "Localisation", ENGLISH: "Location"},
    24: {FRENCH: "Nom du rucher", ENGLISH: "Name of the apiary"},
    25: {FRENCH: "Lieu du rucher", ENGLISH: "Location of the apiary"},
    26: {FRENCH: "Sélectionner...", ENGLISH: "Choose..."},
    27: {FRENCH: "Type de miel", ENGLISH: "Honey type"},
    28: {FRENCH: "Status", ENGLISH: "Status"},
    29: {FRENCH: "Actif", ENGLISH: "Active"},
    30: {FRENCH: "Inactif", ENGLISH: "Inative"},
    31: {FRENCH: "Date de création", ENGLISH: "Creation date"},
    32: {FRENCH: "Nouveau type de miel", ENGLISH: "New honey type"},
    33: {FRENCH: "Annuler", ENGLISH: "Cancel"},
    35: {FRENCH: "Dashboard", ENGLISH: "Dashboard"},
    36: {FRENCH: "Créer une ruche", ENGLISH: "New hive"},
    37: {FRENCH: "Création d'une ruche", ENGLISH: "Creation of a hive"},
    38: {FRENCH: "Stock", ENGLISH: "Stock"},
    39: {FRENCH: "Active", ENGLISH: "Active"},
    40: {FRENCH: "Apiculteur", ENGLISH: "Beekeeper"},
    42: {FRENCH: "État", ENGLISH: "Condition"},
    43: {FRENCH: "Rucher", ENGLISH: "Apiary"},
    44: {FRENCH: "Nouveau propriétaire", ENGLISH: "New owner"},
    45: {FRENCH: "Nouveau status", ENGLISH: "New status"},
    46: {FRENCH: "Mes ruches", ENGLISH: "My hives"},
    47: {FRENCH: "Mes ruchers", ENGLISH: "My apiaries"},
    48: {FRENCH: "Évènement", ENGLISH: "Event"},
    49: {FRENCH: "Modifier la ruche", ENGLISH: "Edit the hive"},
    50: {FRENCH: "Commentaire", ENGLISH: "Comment"},
    51: {FRENCH: "Tous", ENGLISH: "All"},
    52: {FRENCH: "Ruche", ENGLISH: "Hive"},
    53: {FRENCH: "Nouvel état", ENGLISH: "New condition"},
    54: {FRENCH: "Planitifer un évènement", ENGLISH: "Planify an event"},
    55: {FRENCH: "Date visite", ENGLISH: "Visit date"},
    56: {FRENCH: "Commentaire", ENGLISH: "Comment"},
    59: {FRENCH: "Date", ENGLISH: "Date"},
    60: {FRENCH: "Planifier un évènement", ENGLISH: "Planify an event"},
    61: {FRENCH: "Date limite", ENGLISH: "Deadline"},
    63: {FRENCH: "Source", ENGLISH: "Origin"},
    64: {FRENCH: "Supprimer", ENGLISH: "Delete"},
    65: {FRENCH: "EVENEMENT", ENGLISH: "EVENT"},
    66: {FRENCH: "avant le", ENGLISH: "by the"},
    67: {FRENCH: "Memo", ENGLISH: "Memo"},
    68: {
        FRENCH: "Cliquer ici pour marquer comme fait !",
        ENGLISH: "Click here to mark as done !",
    },
    69: {FRENCH: "Marquer l'évènement comme fait", ENGLISH: "Mark the event as done"},
    70: {FRENCH: "Modifier le commentaire", ENGLISH: "Edit comment"},
    72: {FRENCH: "Toutes", ENGLISH: "All"},
    73: {FRENCH: "Nouveau commentaire", ENGLISH: "New comment"},
    74: {FRENCH: "Gestion", ENGLISH: "Manage"},
    75: {FRENCH: "Mot de passe oublié ?", ENGLISH: "Forgot password ?"},
    76: {FRENCH: "Nouveau mot de passe", ENGLISH: "New password"},
    77: {FRENCH: "Confirmer", ENGLISH: "Confirm"},
    80: {FRENCH: "Type de commentaire", ENGLISH: "Comment type"},
    81: {FRENCH: "Paramètre ruche", ENGLISH: "Hives setup"},
    82: {FRENCH: "Paramètre rucher", ENGLISH: "Apiary setup"},
    83: {FRENCH: "Données", ENGLISH: "Data"},
    85: {FRENCH: "Editer", ENGLISH: "Edit"},
    87: {FRENCH: "Edition base de données", ENGLISH: "Edit database"},
    89: {FRENCH: "Ajouter une entrée", ENGLISH: "Add a new entry"},
    90: {FRENCH: "Renommer", ENGLISH: "Rename"},
    91: {FRENCH: "Français", ENGLISH: "French"},
    92: {FRENCH: "Anglais", ENGLISH: "English"},
    93: {FRENCH: "Modifier le rucher", ENGLISH: "Edit apiary"},
    94: {FRENCH: "Supprimer", ENGLISH: "Delete"},
    95: {FRENCH: "Essaims", ENGLISH: "Swarms"},
    96: {FRENCH: "Mes essaims", ENGLISH: "My swarms"},
    97: {FRENCH: "Créer un essaim", ENGLISH: "Create a swarm"},
    98: {FRENCH: "Création d'un essaim", ENGLISH: "Creation of a swarm"},
    99: {FRENCH: "Santé", ENGLISH: "Health"},
    100: {FRENCH: "Nouveau status de santé", ENGLISH: "New health status"},
    101: {FRENCH: "Paramètre essaim", ENGLISH: "Swarm setup"},
    102: {FRENCH: "Modifier l'essaim", ENGLISH: "Edit hive"},
    103: {FRENCH: "Santé de l'essaim", ENGLISH: "Swarm health"},
    104: {FRENCH: "Aucun essaim", ENGLISH: "No swarm"},
    105: {FRENCH: "Aucun évènement de prévu !", ENGLISH: "No event planned !"},
    106: {FRENCH: "Aucun commentaire !", ENGLISH: "No commentary !"},
    107: {FRENCH: "Aucun essaim !", ENGLISH: "No swarm !"},
    108: {
        FRENCH: "Cliquer ici pour créer un nouvel essaim à cette ruche !",
        ENGLISH: "Click here to attach a new swarm to this hive !",
    },
    109: {FRENCH: "Attacher un nouvel essaim", ENGLISH: "Attach a new swarm"},
    110: {FRENCH: "Essaim", ENGLISH: "Swarm"},
    111: {FRENCH: "Historique", ENGLISH: "History"},
    112: {FRENCH: "Évènements", ENGLISH: "Events"},
    113: {FRENCH: "Santé de l'essaim", ENGLISH: "Swarm's health"},
    114: {FRENCH: "Etat de la ruche", ENGLISH: "Hive's condition"},
    115: {FRENCH: "Note", ENGLISH: "Note"},
    116: {FRENCH: "Fait", ENGLISH: "Done"},
    117: {FRENCH: "Valeur", ENGLISH: "Value"},
    118: {FRENCH: "Status d'un rucher", ENGLISH: "Apiary statuses"},
    119: {FRENCH: "Types d'évènement", ENGLISH: "Event types"},
    120: {FRENCH: "Autres actions", ENGLISH: "Other actions"},
    121: {FRENCH: "Deplacer la ruche", ENGLISH: "Move the hive"},
    122: {FRENCH: "Ruche déplacer de {old} vers {new}", ENGLISH: "Hive moved from {old} to {new}"},
}
