apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    app: loki
spec:
  type: ClusterIP
  ports:
  - port: 3100
    targetPort: 3100
  selector:
    app: loki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: loki-data
      containers:
      - name: loki
        image: grafana/loki
        # command: ["tail", "-f", "/dev/null"]
        ports:
        - containerPort: 3100
        volumeMounts:
        - mountPath: /loki
          name: data

