apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail-daemon
spec:
  selector:
    matchLabels:
      name: promtail-daemon
  template:
    metadata:
      labels:
        name: promtail-daemon
    spec:
      serviceAccount: promtail-service-account
      serviceAccountName: promtail-service-account
      volumes:
      - name: promtail-config
        configMap:
          name: promtail-config
      - name: logs
        hostPath:
          path: /var/log
      - name: position
        hostPath:
          path: /position.yaml
          type: FileOrCreate
      containers:
      - name: promtail-daemon
        image: grafana/promtail
        args:
        - -config.file=/etc/promtail/promtail.yaml
        ports:
        - containerPort: 9080
        env:
        - name: 'HOSTNAME'
          valueFrom:
            fieldRef:
              fieldPath: 'spec.nodeName'
        volumeMounts:
        - name: promtail-config
          mountPath: /etc/promtail
        - name: logs
          mountPath: /var/log
        - name: position
          mountPath: /run/promtail/position.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9080
    targetPort: 9080
  selector:
    app: promtail-daemon
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail-cluster-role
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs:
  - get
  - watch
  - list
- apiGroups:
    - extensions
    - networking.k8s.io
  resources:
    - ingresses
  verbs: ["get", "list", "watch"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail-service-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: promtail-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: promtail-cluster-role
  apiGroup: rbac.authorization.k8s.io
