apiVersion: v1
kind: Service
metadata:
  name: aristaeus-api
  labels:
    app: aristaeus-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9002
    targetPort: 9002
  selector:
    app: aristaeus-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aristaeus-api
  labels:
    app: aristaeus-api
spec:
  selector:
    matchLabels:
      app: aristaeus-api
  template:
    metadata:
      labels:
        app: aristaeus-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: elastic-node
                operator: DoesNotExist
      containers:
      - image: yomain/aristaeus:latest
        name: aristaeus-api
        env:
        - name: AKB_SERVICE_NAME
          value: aristaeus-api
        - name: AKB_LOG_FORMAT
          value: json

        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: env-vars-config
              key: ENV

        # APP SECRETS
        - name: AKB_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: env-secrets-config
              key: JWT_SECRET_KEY

        # DATABASE SECRETS
        - name: AKB_DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: env-secrets-config
              key: DATABASE_HOST
        - name: AKB_DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: env-secrets-config
              key: DATABASE_PORT
        - name: AKB_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: env-secrets-config
              key: DATABASE_USER
        - name: AKB_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secrets-config
              key: DATABASE_PASSWORD
        - name: AKB_DATABASE_DBNAME
          valueFrom:
            secretKeyRef:
              name: env-secrets-config
              key: DATABASE_DBNAME

        # Cerbes service
        - name: AKB_CERBES_API_ENDPOINT
          value: cerbes-api
        - name: AKB_CERBES_API_PORT
          value: '9001'

        command: ["uvicorn", "aristaeus.app:app", "--host", "0.0.0.0", "--port", "9002"]
        ports:
        - containerPort: 9002
        readinessProbe:
          httpGet:
            path: /_/status
            port: 9002
        volumeMounts:
        - mountPath: /var/log/aristaeus
          name: logs

      volumes:
      - name: logs
        hostPath:
          type: DirectoryOrCreate
          path: /var/log/akingbee


