apiVersion: v1
kind: Service
metadata:
  name: poseidon
  labels:
    app: poseidon
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9000
    targetPort: 80
  selector:
    app: poseidon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poseidon
  labels:
    app: poseidon
spec:
  selector:
    matchLabels:
      app: poseidon
  template:
    metadata:
      labels:
        app: poseidon
    spec:
      containers:
      - image: yomain/poseidon:1.5.1
        name: poseidon
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: env-vars-config
              key: ENV
        - name: REACT_APP_ARISTAEUS_API
          value: aristaeus-api
        - name: REACT_APP_CERBES_API
          value: cerbes-api
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/log/poseidon
          name: logs

      volumes:
      - name: logs
        hostPath:
          type: DirectoryOrCreate
          path: /var/log/poseidon


