apiVersion: v1
kind: Pod
metadata:
  name: alembic-migration
  labels:
    app: alembic-migration
spec:
  restartPolicy: OnFailure
  containers:
  - name: gaea
    image: yomain/gaea:latest
    env:
    - name: AKB_DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: env-secrets-config
          key: DATABASE_HOST
    - name: AKB_DATABASE_PORT
      valueFrom:
        secretKeyRef:
          name: env-secrets-config
          key: DATABASE_PORT
    - name: AKB_DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: env-secrets-config
          key: DATABASE_USER
    - name: AKB_DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: env-secrets-config
          key: DATABASE_PASSWORD
    - name: AKB_DATABASE_DBNAME
      valueFrom:
        secretKeyRef:
          name: env-secrets-config
          key: DATABASE_DBNAME