[default]
service_name = "aristaeus"
jwt_key = "very_super_secret_key"
zeromq_port = 5555

[development]
database_host = "localhost"
database_port = 5432
database_user = "sa_aristaeus"
database_password = "123"
database_dbname = "aristaeus"

cerbes_api_endpoint = "localhost"
cerbes_api_port = 8000

[compose]
cerbes_api_endpoint = "cerbes"
cerbes_api_port = 9001

[integration]
database_host = "localhost"
database_port = 5432
database_user = "postgres"
database_password = "123"
database_dbname = "postgres"

