DB_URL := "postgres://sa_aristaeus:password@localhost:5432/cerbes"


db:
	docker compose up -d db

init:
	poetry install

test-unit:
	poetry run pytest tests/unit

test-integration: 
	poetry run pytest tests/integration

migrate: db
	poetry run alembic upgrade head

serve: db migrate
	poetry run uvicorn --host 0.0.0.0 --port 8001 --reload src.aristaeus.controllers.api.app:create_app

serve-prod: db migrate
	poetry run gunicorn src.aristaeus.controllers.api.app:create_app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8001

profile-serve: db migrate
	poetry run viztracer -m uvicorn --host 0.0.0.0 --port 8001 --reload src.aristaeus.controllers.api.app:create_app

listen: db migrate
	poetry run python src/aristaeus/controllers/consumers/app.py

lint:
	poetry run black src tests migrations