configMapGenerator:
- name: db-users-setup
  files:
  - config/postgresql/users.sh


bases:
  - ./grafana

resources:
  - ingress-main.yaml
  - ingress-redirect.yaml
  - rbmq.yaml
  - volumes.yaml
  - postgresql.yaml


images:
- name: docker.elastic.co/elasticsearch/elasticsearch
  newTag: 7.15.1
- name: docker.elastic.co/kibana/kibana
  newTag: 7.15.1
- name: docker.elastic.co/beats/filebeat
  newTag: 7.15.1

