apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: elastic-node
                operator: DoesNotExist
      containers:
      - image: postgres:12-alpine
        name: postgres
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: env-vars-config
              key: ENV
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: env-secrets-config
              key: DATABASE_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secrets-config
              key: DATABASE_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: env-secrets-config
              key: DATABASE_DBNAME
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: FIREFLY_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secrets-config
              key: FIREFLY_USERNAME
        - name: FIREFLY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secrets-config
              key: FIREFLY_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: db-users-setup
          mountPath: /docker-entrypoint-initdb.d/
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-data
      - name: db-users-setup
        configMap:
          defaultMode: 0770
          name: db-users-setup