apiVersion: v1
kind: Service
metadata:
  name: rbmq
  labels:
    app: rbmq
spec:
  type: NodePort
  ports:
    - name: worker
      port: 5672
      targetPort: 5672
    - name: graph
      port: 15672
      targetPort: 15672
  selector:
    app: rbmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbmq
  labels:
    app: rbmq
spec:
  selector:
    matchLabels:
      app: rbmq
  template:
    metadata:
      labels:
        app: rbmq
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: elastic-node
                operator: DoesNotExist
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rbmq-data
      containers:
      - image: rabbitmq:management-alpine
        name: rbmq
        env:
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: env-secrets-config
              key: RBMQ_ERLANG_COOKIE
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: env-secrets-config
              key: RBMQ_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: env-secrets-config
              key: RBMQ_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /var/lib/rabbitmq/data


