SUBJECT = "Subject"
TO = "To"
SENDER = "Sender"
CC = "Cc"
BCC = "Bcc"

EMAIL_FIELDS = (SUBJECT, SENDER, TO, CC, BCC)
MANDATORY_EMAIL_FIELDS = (SUBJECT, TO, SENDER)

EMAIL_SERVER_HOST = "smtp.zoho.eu"
EMAIL_SERVER_PORT = 465

EMAIL_ADDRESS_NO_REPLY = "noreply@akingbee.com"
