"""add harvest model

Revision ID: 7d2caa82eeff
Revises: f998571c548b
Create Date: 2023-08-18 14:12:33.107674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d2caa82eeff"
down_revision = "f998571c548b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("harvest", sa.Column("date_harvest", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("harvest", "date_harvest")
    # ### end Alembic commands ###
