"""add harvest model

Revision ID: f998571c548b
Revises: 95891afca307
Create Date: 2023-07-18 22:26:21.743383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f998571c548b"
down_revision = "95891afca307"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "harvest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("apiary_name", sa.Text(), nullable=False),
        sa.Column("hive_id", sa.Integer(), nullable=False),
        sa.Column("date_creation", sa.DateTime(), nullable=False),
        sa.Column("date_modification", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hive_id"],
            ["hive.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("harvest")
    # ### end Alembic commands ###
