DEFAULT:
  SERVICE_NAME: "hermes"
  LOG_LEVEL: 20
  ZEROMQ_PORT: 5555

DEVELOPMENT:
  LOGS_FOLDER_NAME: "log"

  NOREPLY_EMAIL: "noreply@byebye.com"

  RBMQ_PORT: 5672
  RBMQ_HOST: "127.0.0.1"
  RBMQ_USER: "akingbee"
  RBMQ_PASSWORD: "password"
  RBMQ_VHOST: "/"

