clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: syslog

    static_configs:
      - targets: [localhost]
        labels:
          __path__: /var/log/*.log

  - job_name: akingbee

    static_configs:
      - targets: [localhost]
        labels:
          source: akingbee
          __path__: /var/log/akingbee/*

    pipeline_stages:
      - json:
          expressions:
            job: name
            user_id: user_id
            user_email: user_email
            hive_id: hive.id
            apiary_id: apiary.id
            message: message
            duration: duration
            levelname: levelname
            timestamp: timestamp
            status_code: status_code
            request_method: request_method
            request_ip_address: request_ip_address
            request_form: request_form
            pathname: pathname
            request_path: request_path
            lineno: lineno
            funcName: funcName
            request_user_agent: request_user_agent
            exc_info: exc_info
            extra: extra
      - template:
          source: log_message
          template: '{{.job}}{{ print "\t"}}{{ or .levelname "    " }}{{ print "\t" }}{{or .status_code "   " }}{{print "\t"}}{{ if .user_id }}{{ if ne .user_id "0" }}user {{ .user_id }}{{end}}{{end}}{{print "\t\t"}}{{or .request_ip_address "            " }}{{print "\t"}}{{ .message }}'
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          job:
          user_id:
          user_email:
          hive_id:
          apiary_id:
          message:
          duration:
          levelname:
          status_code:
          pathname:
          lineno:
          funcName:
          request_path:
          request_form:
          request_method:
          request_ip_address:
          request_user_agent:
      - output:
          source: log_message

