configMapGenerator:
- name: env-vars-config
  env: dev.env

secretGenerator:
- name: env-secrets-config
  env: dev.secrets

bases:
- ../../applications
- ../../core
- ../../jobs

resources:
- letsencrypt.yaml

vars:
- name: MAIN_HOSTED_ZONE
  objref:
    kind: ConfigMap
    name: env-vars-config
    apiVersion: v1
  fieldref:
    fieldpath: data.DNS
