FROM python:3.7-alpine

# update & install librairies
RUN apk update && \
    apk add openrc gcc libc-dev pcre-dev pcre linux-headers coreutils bash sudo \
            python3-dev py-setuptools vim mariadb mysql mysql-client mariadb-client \
            mariadb-connector-c-dev


