name: akingbee

defaults:
  run:
    shell: bash

jobs:
  validation:
    name: lint & pytest
    runs-on: ubuntu-latest

    env:
      AKB_DATABASE_HOST: localhost
      AKB_DATABASE_PORT: 5432
      AKB_DATABASE_USER: dbtest
      AKB_DATABASE_PASSWORD: dbtest
      AKB_DATABASE_DBNAME: dbtest

    steps:
      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
      - name: checkout
        uses: actions/checkout@v4
      - name: install project
        run: go mod download
      - name: run go fmt
        run: go fmt
