configMapGenerator:
- name: env-vars-config
  env: production.env
  namespace: default
  options:
    disableNameSuffixHash: false

secretGenerator:
- name: env-secrets-config
  env: production.secrets
  options:
    annotations:
      kustomize.config.k8s.io/behavior: replace
    disableNameSuffixHash: false
  namespace: default

- name: google-api-token
  files:
    - tokens/google-credentials.json
  options:
    annotations:
      kustomize.config.k8s.io/behavior: replace
    disableNameSuffixHash: false
  namespace: default



bases:
- ../../applications
- ../../core
- ../../jobs

resources:
- letsencrypt.yaml
- secrets.yaml

vars:
- name: MAIN_HOSTED_ZONE
  objref:
    kind: ConfigMap
    name: env-vars-config
    apiVersion: v1
  fieldref:
    fieldpath: data.DNS
